### ISSUE TITLE
Tests missing

### ISSUE THREAD

**Issue by sai-krishna-msk** [ashwinvin/Visionlib#2]
Hey if you intending to make this open source and you would want to safely accept/reject pull request then it's a good idea to have tests(unit tests) right..

**Comment by sai-krishna-msk** [comment]
I guess it's not a bug, a suggestion rather so I am closing it

**Comment by ashwinvin** [comment]
> I guess it's not a bug, a suggestion rather so I am closing it

Enhancement is probably more suited. I am will try to implement it.
Any help is appreciated

**Comment by ashwinvin** [comment]
Tests have added in commit 973566952 and automated in d676a02ff. Thanks for raising the issue.
